import Navbar from '@/components/Navbar'
import Providers from './Providers'
import './globals.css'



export const metadata = {
  title: 'NextAuth',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Navbar/>
          {children}
        </Providers>
      </body>
    </html>
  )
}
